version: "3.3"
services:
  npm:
    container_name: nykk-btn
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/nykk-btn
      - /usr/src/nykk-btn/node_modules
    working_dir: /usr/src/nykk-btn
    entrypoint: npm
